version: '3'
services:
  bot:
    build: .
    image: $APP_IMAGE
    env_file:
      - .env
    restart: always
  cache:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '$CACHE_PORT:$CACHE_PORT'
    command: redis-server --save 20 1 --loglevel warning --requirepass $CACHE_PASSWORD
    volumes:
      - redis_data:/data

volumes:
  redis_data:
