version: '3'

networks:
  api_network:

services:
  bot:
    build: .
    image: $APP_IMAGE
    env_file:
      - .env
    restart: always
    networks:
      - api_network
    logging:
      driver: json-file
      options:
        max-size: 50m
  postgres:
    image: postgres:alpine
    command: -p $POSTGRES_PORT
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - api_network
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: